### ISSUE TITLE
No need to fill out the values in LUCI, right?

### ISSUE THREAD

**Issue by yukeiyang** [aa65535/openwrt-simple-obfs#4]
After install this ipk in openwrt, I fill out the values at luci UI:

"plugin":    "obfs-local", 
"plugin_opts":    "obfs=http;obfs-host=www.baidu.com"

But unfortunately, can not access the internet.
So, no need to put the values at LUCI end, right?

**Comment by aa65535** [comment]
If the server does not have a configuration plugin, leave it blank.

For more details, see https://github.com/shadowsocks/simple-obfs

**Comment by yukeiyang** [comment]
In my case, simple-obfs already installed & configured at server end. 

If leave it blank at LUCI end, Does simple-obfs still work in openwrt?

**Comment by aa65535** [comment]
You need to configure plugin on the client side.

Can you give me a screenshot of the server settings?

**Comment by yukeiyang** [comment]
{
    "server":"139.52.156.51",
    "server_port":443,
    "local_port":1080,
    "password":"*********",
    "timeout":60,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=http",
    "method":"chacha20-ietf"
}

**Comment by aa65535** [comment]
@yukeiyang client side?

**Comment by yukeiyang** [comment]
Server Side.

**Comment by aa65535** [comment]
@yukeiyang What is the client side settings?

**Comment by yukeiyang** [comment]
I installed  shadowsocks-libev_******.ipk , not installed
shadowsocks-libev-server_******.ipk at openwrt router end. is it right?


No config.json file exists at openwrt router end for /etc/shadowsocks-libev


So, I can only configured at LUCI for obfs

**Comment by aa65535** [comment]
@yukeiyang 

>I installed  shadowsocks-libev_******.ipk , not installed
shadowsocks-libev-server_******.ipk at openwrt router end. is it right?

Right!

>No config.json file exists at openwrt router end for /etc/shadowsocks-libev
So, I can only configured at LUCI for obfs

Use `uci export shadowsocks` to view the configuration on openwrt.

**Comment by yukeiyang** [comment]
**AT Openwrt Router End:**

root@OpenWrt:~# uci export shadowsocks
package shadowsocks

config general
        option startup_delay '5'

config transparent_proxy
        option local_port '1234'
        option main_server 'cfg0a4a8f'
        option udp_relay_server 'same'
        option mtu '1492'

config socks5_proxy
        option local_port '1080'
        option server 'cfg0a4a8f'
        option mtu '1492'

config port_forward
        option local_port '5300'
        option destination '8.8.4.4:53'
        option server 'cfg0a4a8f'
        option mtu '1492'

config servers
        option auth '0'
        option fast_open '0'
        option timeout '60'
        option server '130.19.108.66'
        option server_port '443'
        option password '*******'
        option encrypt_method 'chacha20-ietf'
        option plugin 'obfs-local'

config access_control
        option self_proxy '1'
        option wan_bp_list '/etc/chinadns_chnroute.txt'
        option lan_target 'SS_SPEC_WAN_AC'

**Comment by aa65535** [comment]
`plugin_opts`  can not be empty.

try
```
uci set shadowsocks.cfg624417.plugin_opts='obfs=http;obfs-host=www.bing.com'
uci commit shadowsocks
```

**Comment by yukeiyang** [comment]
**I run this:**
uci set shadowsocks.**cfg0a4a8f**.plugin_opts='obfs=http;obfs-host=www.bing.com'
uci commit shadowsocks

**I tried to  edit manually too as below:** 
**vi /etc/config/shadowsocks**
# add this to "config servers"
option plugin 'obfs-local'
option plugin_opts 'obfs=http;obfs-host=www.bing.com'

But all failed to  access the blocked sites when add plugin_opts.

**Comment by aa65535** [comment]
restart server side.

**Comment by yukeiyang** [comment]
I did for restart at server side.  It's strange. still can not access the blocked sites.

**Comment by aa65535** [comment]
simple-obfs installed?

**Comment by yukeiyang** [comment]
yes.  installed yet.

**in the server end:**
$ cd /usr
$ git clone https://github.com/shadowsocks/simple-obfs.git
$ cd simple-obfs
$ git submodule update --init --recursive
$ ./autogen.sh

**in the openwrt client**
$ wget https://dl.bintray.com/aa65535/openwrt/simple-obfs/0.0.2/OpenWrt/ramips/:simple-obfs_0.0.2-1_ramips_24kec.ipk
$ opkg istall simple-obfs_0.0.2-1_ramips_24kec.ipk

**Comment by yukeiyang** [comment]
**in the server end:**
$ ss-server -c config.json --plugin obfs-server --plugin-opts "obfs=http"

**the result:**
ss-server: unrecognized option '--plugin-opts'

So, how can i enable  option '--plugin-opts'?

**Comment by aa65535** [comment]
@yukeiyang upgrade ss-server,  v3.0.0 or above.

**Comment by yukeiyang** [comment]
@aa65535  Great. Success. The error gone when upgrade to 3.0.3 by Compile Install.
thanks.

**Comment by ssluciwrt** [comment]
@aa65535  Sorry to bother you 
In my case ,everything has worked fine after I added obfs in my server & router end config as a plugin,but the server-end has obfs-server process running while there is no obfs-local process running in the router-end,,really don't know how to make sure that it effects.
BTW,I uses the netstat -tunlp & ps | grep obfs-local for checking.
